{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.appName }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "hook-succeeded"  # Add this: Deletes only after success
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: roboshop-secret-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.appName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.appName }}
{{- end }}
