{{- if eq (include "externalSecrets.canRender" .) "true" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.appName }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: roboshop-secret-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.appName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.appName }}
{{- end }}